# Generated by Django 2.0 on 2018-01-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='description',
        ),
        migrations.RemoveField(
            model_name='list',
            name='owner',
        ),
    ]
